#!/bin/sh

# Check if we actually have commits to push
commits=`git log @{u}..`
if [ -z "$commits" ]; then
    exit 0
fi

# Run tests
make test

RESULT=$?
if [ $RESULT -ne 0 ]; then 
	echo "Tests failed."
	exit 1
fi

exit 0
